"""empty message

Revision ID: 049b98bb5121
Revises: e5403937cdad
Create Date: 2024-04-02 06:15:56.511453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049b98bb5121'
down_revision: Union[str, None] = 'e5403937cdad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('staff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'staff')
    # ### end Alembic commands ###
