"""empty message

Revision ID: 5bfce5330ad6
Revises: 049b98bb5121
Create Date: 2024-04-09 00:43:48.957262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfce5330ad6'
down_revision: Union[str, None] = '049b98bb5121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=False))
    op.drop_column('user', 'staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('staff', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
